### ISSUE TITLE
Security: Should token be hidden?

### ISSUE THREAD

**Issue by kodaman2** [lauthieb/code-notes#100]
**Describe the bug**
I don't know if this is a valid security issue, but I believe the token once stored it should not be visible at all kind of like on github. I haven't done much Vue to be honest, so even is is hidden I don't know if the store is still accessible via file directory.

**To Reproduce**
1. Go to settings
2. Token is visible

**Expected behavior**
Token should be perhaps hidden after saving, and some sort of obfuscation in the store?

Anyways I thought to open the issue maybe someone with more experience in security can share their thoughts.

**Comment by jack-chapman** [comment]
I'd be happy to implement a fix for this. Makes sense to me that you wouldn't want someone else to see your token!

**Comment by jack-chapman** [comment]
This could be done by handling the input like a password?

So, unless you click the eye icon, the token will be hidden. This would hopefully prevent somebody from seeing it on your screen.

<img width="592" alt="Screenshot 2019-10-20 at 16 43 36" src="https://user-images.githubusercontent.com/25803013/67162089-d0f68800-f358-11e9-8ebc-ac5df53448f3.png">

**Comment by jack-chapman** [comment]
Could potentially do a base64 encode too in the store?

**Comment by kodaman2** [comment]
Jack yeah I understand the visual aspect that's one quick fix for sure.

I am more interested in the token stored within the system. Where some hacker can intentionally grab that token since is plain text and use it maliciously. I know is far fetched. 

If you launch code notes in dev, you can still see the token by drilling down the vue components. My question, since I am relatively new to web dev can this token be stored securely?

**Comment by jack-chapman** [comment]
> I am more interested in the token stored within the system. Where some hacker can intentionally grab that token since is plain text and use it maliciously. I know is far fetched.

Yeah I see your point here. I'm not sure _where_ the data is actually stored on the user's machine, so I'm not sure how to check if it's usable or not. @lauthieb could you offer any advice on this?

> If you launch code notes in dev, you can still see the token by drilling down the vue components. My question, since I am relatively new to web dev can this token be stored securely?

As I mentioned above, we could obfuscate the token in the store by doing some kind of base64 encode and only decoding it upon render, however I don't know how useful or worthwhile this will be — I don't think it's that likely for an user (who isn't the token's owner and without dev tools) to find the raw access token.

**Comment by kodaman2** [comment]
Yeah I don't see much of an issue for a single user machine, but a multiple user computer might be an issue maybe not so much on Linux/mac where files are protected per user per chmod permissions. On windows it might be a different story as long as you have admin rights you can read any file. I guess most tokens will be useless if is just a gists permission but imagine if someone accidentally gave all permissions you have access to entire accounts. 

Look at #40 I am almost certain settings.db will be plain text, but not sure because I've been working off the dev version.

Encoding won't really work since this repo is open source anyone will know how to decode, but imo it would be better to password protect the settings file, remember github doesn't even let you see the token ever again so I think we should treat it with the same level of protection. I also understand this might be hard to do.

**Comment by jack-chapman** [comment]
> Look at #40 I am almost certain settings.db will be plain text, but not sure because I've been working off the dev version.

Yep, it is. I'm afraid I don't have a solution for that one.

I'll make another issue and PR for hiding the access token behind a password field however — as that definitely should be done.

**Comment by lauthieb** [comment]
Thanks a lot for this investigation.
I don't have any idea too to hide this token on the computer.
Maybe this could be done with a support of Dashlane/Keypass integration. But I've never did that with an Electron application. :)

**Comment by kodaman2** [comment]
Yeah I don't know much about security within storages, I just put it out there in case is something to be done. It might not be a big deal after all.

**Comment by LucasVanHaaren** [comment]
Hi guys, after some research, I found this node module : [keytar](https://github.com/atom/node-keytar) 

This module delegates the storage of the token to the key/password manager of each OS.

> On macOS the passwords are managed by the Keychain, on Linux they are managed by the Secret Service API/libsecret, and on Windows they are managed by Credential Vault.

I think that can solve the problem.

**Comment by lauthieb** [comment]
Oh nice @LucasVanHaaren, thanks a lot for this idea! 💡

**Comment by LucasVanHaaren** [comment]
Hi everyone,
I can give a try to implement it in the next few weeks.

As the official documentation says, on linux distributions this module depends on native packages:
- Debian: _libsecret-1-dev_
- RedHat: _libsecret-devel_
- Arch: _libsecret_

So I think we should also write an npm pre-installation script to check / install the corresponding packages.
What do you think about this ?

**Comment by kodaman2** [comment]
I think you should definitely implement it! 👍😁 password managers are a lot better than plain text.

Have a look here for custom scripts to check dependencies.
 https://stackoverflow.com/q/45082648/1013828

**Comment by lauthieb** [comment]
Completely agree with @kodaman2.
Let's go :rocket:
