### ISSUE TITLE
Menu -> Application -> About application is not working

### ISSUE THREAD

**Issue by probil** [lauthieb/code-notes#104]
**Describe the bug**
Menu -> Application -> About application is not working

**To Reproduce**
1. Open app
2. Click `Menu -> Application  -> About application`

**Expected behavior**
_About screen_ is displayed

**Additional context**
App version: 1.2.2

**Comment by lauthieb** [comment]
Oh strange, it works on MacOS. What's your OS?

![image](https://user-images.githubusercontent.com/9600228/67053139-c2358880-f140-11e9-8ab5-7e9bdad7af09.png)

**Comment by probil** [comment]
Hi @lauthieb 
```
OS: Linux
Distrubution: ArchLinux (Anteros)
Desktop Environment: Cinnamon
```

**Comment by liloumuloup** [comment]
Hello !

I've got the same case on Windows 10 Pro

**Comment by mszkb** [comment]
It is a feature for macos only. See https://github.com/electron/electron/issues/12677#issuecomment-383165627.
There is a npm package which solves this problem: https://www.npmjs.com/package/electron-about-window

Either we use the npm package or we create our own window.

**Comment by lauthieb** [comment]
Oh thanks @mszkb, @probil do you want to test this solution?

**Comment by mszkb** [comment]
We can maybe add this after we upgraded to vue-cli 4. Before that I do not like to do any pull requests, because the structure changed there :)

**Comment by pahosler** [comment]
I have a fix for this, but it required some minor rewriting of the code. I currently only have Windows 10 to test on, but the changes shouldn't cause any issues with other OS's. Also it moves the about modal into `src/components/modals/about-modal` and out of `Navbar.vue`

**Comment by mszkb** [comment]
Yeah go ahead @pahosler, I do not have time to do this right now :)
