### ISSUE TITLE
Feature request : backup and export/import feature

### ISSUE THREAD

**Issue by liloumuloup** [lauthieb/code-notes#108]
Hello,

I would like to know if it's possible to add a way to backup the datas easily and on another drive or in another folder ?

Is there also a way to export and reimport the datas ?

Kind regards.

**Comment by lauthieb** [comment]
Hi thanks @liloumuloup!
There's no possible for the moment and I don't have any time to do this development...
But your request is more detailed here : Duplicate #40 
Regards.
