### ISSUE TITLE
App icon on linux broken

### ISSUE THREAD

**Issue by OiYouYeahYou** [lauthieb/code-notes#109]
**Describe the bug**
On Ubuntu the app icon is either not set or missing

**To Reproduce**
Steps to reproduce the behaviour:
1. Download app image
1. Run app image on Ubuntu
1. Look at app icon in the dock/app-bar
1. Observe that it is the "iconless icon" given to apps without icons

**Screenshots**
![image](https://user-images.githubusercontent.com/20130059/67485665-731cb580-f662-11e9-92e1-1e6bc304ab80.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04 with GNOME

**Additional context**
Willing to accept PR? It's often an easy fix

**Comment by lauthieb** [comment]
Just PNG sorry :(

**Comment by lauthieb** [comment]
You can crop this image : https://github.com/lauthieb/code-notes/blob/master/src/renderer/assets/img/code-notes-logo-black-full.png
and convert to SVG if you want.

**Comment by kodaman2** [comment]
Is this still an issue? I used lubuntu, and icon works fine on that one, I don't have ubuntu VM and I don't like the distro lol.

Can you please go to ~/.local/share/applications or whatever path your .desktop file is, and show us the contents of that files. It should be called appimagekit-code-notes.desktop

I believe this is an electron issue as per the two issues below:
https://github.com/electron-userland/electron-builder/issues/2269
https://github.com/electron-userland/electron-builder/issues/748

Can you try on `src/main/index.js` adding inside BrowserWindow:

```
mainWindow= new BrowserWindow({
   ...
   icon: path.join(__dirname, '/build/icons/256x256.png')
})

```

Then do a build test, and let us know if it worked, some users on those thread said yes other no:

```
npm run build
```

**Comment by OiYouYeahYou** [comment]
I cloned a fresh copy of master and made the suggested changes. The icon still doesn't work unfortunately

```diff
diff --git a/src/main/index.js b/src/main/index.js
index cc380f6..f244bb0 100644
--- a/src/main/index.js
+++ b/src/main/index.js
@@ -1,4 +1,5 @@
 import { app, BrowserWindow, Menu } from 'electron'; // eslint-disable-line
+import { join } from 'path';
 
 /**
  * Set `__static` path to static files in production
@@ -27,6 +28,7 @@ function createWindow() {
     width: 1160,
     minHeight: 500,
     minWidth: 900,
+    icon: join(__dirname, 'build/icons/255x256.png'),
   });
 
   mainWindow.loadURL(winURL);
```

@kodaman2 as an aside: lubuntu, ubuntu, kubuntu and xubuntu are all the same distribution. The only major difference is which `{,l,k,x}ubuntu-desktop` package is installed. And installing the different DE is just a matter of running `sudo apt install [,l,k,x]ubuntu-desktop`

**Comment by kodaman2** [comment]
If is all the same, then I dunno, it works perfect on my lubuntu. Btw you have a typo on the diff you pasted. 255x256.png, might want to to try 256x256.png

**Comment by OiYouYeahYou** [comment]
The typo makes no difference :(

**Comment by kodaman2** [comment]
Any errors on console?

**Comment by kodaman2** [comment]
I've ran Ubuntu 19.04 with gnome with no issues. Not much I can think of to debug this issue if is working on 3 different linux systems, I've tried.

![image](https://user-images.githubusercontent.com/10265682/72683739-7aa3fd00-3a9f-11ea-9b09-60763f0924e9.png)


![image](https://user-images.githubusercontent.com/10265682/72683747-8f809080-3a9f-11ea-9f0f-6268a88cf0cb.png)

![image](https://user-images.githubusercontent.com/10265682/72683772-dff7ee00-3a9f-11ea-8899-a7b69bb8addb.png)
