### ISSUE TITLE
Scrollbar on screen

### ISSUE THREAD

**Issue by lnrdnl** [lauthieb/code-notes#116]
It's a small thing but I noticed it and I decided to log it.

The main screen always has a scroll bar. But when opening the "create code modal", the scrollbar disappears, and this causes the content to shift in the background. The about modal does not have this problem. I added screenshots as an example.

1. On mainscreen scrollbar always visible
2. Click on [+] (Create Note)
3. Scrollbar disappears

**Expected behavior**
Scrollbar stays.

**Screenshots**
![image](https://user-images.githubusercontent.com/3043203/70127381-3689a400-167b-11ea-8570-d107eb68d809.png)

![image](https://user-images.githubusercontent.com/3043203/70127427-502aeb80-167b-11ea-99bd-3656b0532e41.png)

![image](https://user-images.githubusercontent.com/3043203/70127481-6a64c980-167b-11ea-99b8-487626d72016.png)

**Desktop (please complete the following information):**
 - OS: Win10

**Comment by lnrdnl** [comment]
I really like your project, and I'm planning to do some work on it during Christmas holidays.

**Comment by lauthieb** [comment]
Thanks a lot @lnrdnl for these words, your issue and your time for Code Notes.
Nice to meet you :)

**Comment by lauthieb** [comment]
It's our project :)
