### ISSUE TITLE
Upgrade from 1.2.2 to 1.2.3 blank screen

### ISSUE THREAD

**Issue by torr6420** [lauthieb/code-notes#118]
Hello,

When I installed version 1.2.3 it opened up with a blank screen and now I can't access my code. 
How can I access my code notes.

Thanks

**Comment by lauthieb** [comment]
Sorry @torr6420, I haven't got this problem on my laptop... We will wait if someone has the same problem.

**Comment by lauthieb** [comment]
We will try to fix this issue here : #119

**Comment by torr6420** [comment]
Hello,

Can you please send me a link to download the previous version 1.2.2.

Thanks

**Comment by lauthieb** [comment]
Yes no problem : https://lauthieb.github.io/code-notes/#download

**Comment by torr6420** [comment]
I reinstall it and reloaded the code-notes folder and was able to recover
my notes.

  Thank you very much!
