### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by pierre-67** [lauthieb/code-notes#12]
Thanks a lot for that utilitie.
I had like to be able to add a new language to the list.

**Comment by lauthieb** [comment]
Hello Pierre !
Thanks for your proposition. I understand your request but I depend on the ace editor modes. If you go to src/renderer/main.js, you will see that I import a list of modes and when you select a language, I bind automatically the language to it.
So if you want to add an other language, I should import this mode and if it doesn’t exist, it will be difficult...
Do you have an other idea ?

**Comment by lauthieb** [comment]
Now, it's duplicate of #16 
I will try to plan this on the v1.3.0 ;)
