### ISSUE TITLE
Trouble with eslint line break style on Windows

### ISSUE THREAD

**Issue by lnrdnl** [lauthieb/code-notes#120]
People on Windows, I'm having trouble building the application because of Eslint.

It fails because of line break style rule. I tried to disable it in eslint with ```"linebreak-style:": 0,``` but it keeps complaining:

```
✘ 1162 problems (1162 errors, 0 warnings)

Errors:
  1162  http://eslint.org/docs/rules/linebreak-style
```

When I add ``` * ``` in eslintignore, application is building and no problems. How do you do it @kodaman2 ?

**Comment by kodaman2** [comment]
You'll have to run `npm run eslint:fix` to fix linting issues.

**Comment by kodaman2** [comment]
There's a way to setup your editor to comply with certain linebreaks too might be the long term solution.
