### ISSUE TITLE
Uninstall on windows leaving data behind in roaming folder

### ISSUE THREAD

**Issue by kodaman2** [lauthieb/code-notes#124]
This is merely a TODO note for me lol. I will fix the build configuration on package.json to fix this. I've noticed it on windows only, but I will check on linux and mac too so we can have a clean install/uninstall.

**Comment by kodaman2** [comment]
Data left behind on windows after using unistaller is on following paths:

- %HOME%/AppData/Roaming/Code Notes/installer.exe and logs
- %HOME%/AppData/Roaming/code-notes/user data

**Comment by mszkb** [comment]
There is a nice documentation about the installer and uninstall part of an electron project: https://www.electron.build/configuration/nsis.
I will look into it in the next few days.

**Comment by lauthieb** [comment]
Nice! Thanks @mszkb for this, because I haven't got any Windows laptop...

**Comment by kodaman2** [comment]
This issue was resolved in PR #125 forgot to close the issue.
