### ISSUE TITLE
Are Vue Tools working for everyone?

### ISSUE THREAD

**Issue by kodaman2** [lauthieb/code-notes#127]
I remember Vue tools used to work nicely at some point, now I get a bunch of errors at the end of `npm run dev`, anyone have a workaround is driving me insane. Been searching forever for a solution.

```
┏ Electron -------------------

  Debugger listening on ws://127.0.0.1:5858/0f8f45a8-a340-4e2b-9276-37e1b2063253
  For help see https://nodejs.org/en/docs/inspector

┗ ----------------------------

┏ Electron -------------------

  [2828:0109/200719.238:ERROR:CONSOLE(1)] "Uncaught SyntaxError: Unexpected token ...", 
source: chrome-extension://vue-js-devtools/build/devtools.js (1)

┗ ----------------------------
```

**Comment by lauthieb** [comment]
Same here, I don't know why :/

**Comment by kodaman2** [comment]
On a good note is still working on my mac, which might have something different. I'll have to compare global packages versions. I used master branch and I can see vue tools.

**Comment by kodaman2** [comment]
On my mac I have, where vue tools stil work:

```
node 10.16.0
npm 6.9.0
```

On windows 10 where it doesn't work:

```
node 12.13.1
npm 6.12.1
```

I supposed node doesn't have virtual environments like python? So I can test out my theory without uninstalling installing my global installations?

**Comment by kodaman2** [comment]
I've installed same versions as I have on my mac, and same outcome. At least we know is not a code notes issue, and not an npm issue. Will close for now if I find anything useful. I'll open a new issue for the community.

**Comment by mauricioaznar** [comment]
Did you find any solutions?. I am having the same problem. Maybe if we could manually install another vue js devtools version, it could work.

**Comment by kodaman2** [comment]
I didn't find any solutions for either Linux or Windows. My mac still works but I have no explanation why lol.

**Comment by mauricioaznar** [comment]
Sad. If you ever need to use it on windows, this library worked for me: https://github.com/zce/vue-devtools.
