### ISSUE TITLE
Search within files 

### ISSUE THREAD

**Issue by S0U1SB4N3** [lauthieb/code-notes#128]
**Is your feature request related to a problem? Please describe.**

upgrade your search to include <search>within:file

add above to your search bar and it should return better results 

ive tested this into the gist searcher and it works. 
if I have a file name tail.sh 
and I search tail 
it will only show the file name tail.sh in the results 

however if I type tail -f within:file 

I get  test.sh now in my results because the file contains code with the line tail -f in it. 

just helping you out :)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lauthieb** [comment]
Pretty good idea. Thanks a lot @S0U1SB4N3 and feel free to contribute. I would love to help you.
