### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by Julienh** [lauthieb/code-notes#13]
Hi and thanks for Code Notes :)

Here is some ideas to improve your software : 
- be able to resize the edit view
- choose the save folder for the snippets => I would like to have my snippets on different computer so if it possible save my snippets on dropbox.

Thank you

**Comment by lauthieb** [comment]
Hello Julien, you're welcome ;)

Thanks for your ideas !
For the first, no problem, it's a cool idea and I will try to add this. For the second, I currently develop a version with the integration of Github Gists and maybe one day I will develop a version where we could be able to import/export our code notes :)

**Comment by Julienh** [comment]
Thanks!

Where are saved our widgets ? Maybe if we can have settings to choose the save folder it's enough for my case ;)

**Comment by shevabam** [comment]
Hi,

Thanks for Code Notes !
I have some ideas too :)

* Have the ability to order languages in the sidebar
* Favorite notes (star)
* In the list of notes, have the ability to open / hide each block

Thanks

**Comment by lauthieb** [comment]
Okay, thanks for your ideas guys !

@Julienh, our notes are stored in the userData directory. Refering to the documentation of Electron, this directory is for storing your app's configuration files, which by default it is the appData directory appended with your app's name.
When the gist integration will be up, we will be able to set some configurations, so after that I will try to answer your request ;)

@shevabam a lot of good ideas, I write that in the trello and I will keep you informed about the progression ;)

I do it in my free time, so please be indulgent 😀

Thanks

**Comment by brihx** [comment]
Hello,

Some ideas too.

- keep window size  andposition on restart (OSX?)
- a tag cloud on the left

Thanks for this app :-)

**Comment by AlexShevyakov** [comment]
Hi there,
Fully support a dropbox idea, just to be able to place local database file into specific folder, say Dropbox. No need to create import/export atm.
