### ISSUE TITLE
Garbage local notes file

### ISSUE THREAD

**Issue by fabiograz** [lauthieb/code-notes#130]
Hi,
I look at notes.db content and find that it include also notes I've deleted.
I think, It is useful to have a sort of garbage of deleted notes during closing, or at request so to reduce file size.

Thanks,
Fabio.

**Comment by lauthieb** [comment]
Thanks Fabio for this proposition of enhancement.

**Comment by kodaman2** [comment]
Are the deleted notes on notes.db on next launch?

- Close the app
- Launch the app
- Check notes.db

I'm pretty sure I check this last time, but going off memory. Can you please confirm.

**Comment by fabiograz** [comment]
Ok, you are right.
If  I delete a note, and close application it is yet in notes.db. When I reopen application it is removed from notes.db.
I close the issue.
Thanks,
Fabio.

**Comment by lauthieb** [comment]
Thanks @fabiograz and @kodaman2 for this investigation!
Enjoy Code Notes :-)
