### ISSUE TITLE
Dark Mode + Mysql Connection

### ISSUE THREAD

**Issue by BlackMix** [lauthieb/code-notes#131]
**Is your feature request related to a problem? Please describe.**
Nop.

**Describe the solution you'd like**
I added dark mode and added Mysql option to connection and create
note in DB, I think this is very good. watch that video, demo about it.
dark mode still not complete, need fix some colors.

**Describe alternatives you've considered**
click on image
[![Video](https://i.imgur.com/j7EyvBt.png)](https://www.youtube.com/watch?v=brivHzhbvpkI)

**Additional context**
if ppl like I can do PR.

Edit: fixed dark mode, finished.

**Comment by BlackMix** [comment]
fixed dark mode https://www.youtube.com/watch?v=brivHzhbvpk

**Comment by kodaman2** [comment]
Hey @blackmix I think these two changes should be done in separate PRs. One is gui, the other backend. 

How are you implementing dark mode? Are you allowing for future development such as people making their own templates perhaps on a json file or through the gui? Sorry if the question is redundant I haven't looked at the code yet.

**Comment by BlackMix** [comment]
Hi @kodaman2 
dark mode is in sass tag html.dark, like same as Vue uses in vue-cli
I save option in settings, so every reload still using dark mode.

Mysql just added other settings and edited sidebar for add new menu
and Node.js file with mysql package.

making own templates is good idea, I need see how could create it using some 
template data, looks nice.

**Comment by BlackMix** [comment]
I think to make it more dynamic I could edit the entire menu and let it auto complete, if the person does not use mysql or gist the menu should not appear, I also discovered bugs in the .db files, they always add a new line with the same settings .

**Comment by lauthieb** [comment]
Hi guys, thanks for your answers!
For dark mode, I've put my opinion in the PR #132 comments ;-)

**Comment by lauthieb** [comment]
What's the capital gain of using a MySQL DB instead of simple .db file?

**Comment by BlackMix** [comment]
> 
> 
> What's the capital gain of using a MySQL DB instead of simple .db file?

I'll edit it, but good for use in remove server, if ppl not like save in local machine

**Comment by kodaman2** [comment]
I'll put my two cents, most end users will probably not want to setup mysql and a database just for gists. I think in the grand scheme of things something like Dropbox or Google for syncing local notes might be more beneficial than additional the whole overhead of a full blown database.

Actually all of the above could be forgotten, if a local note had a button to convert to gists then is on github forever. :wink:

**Comment by BlackMix** [comment]
yeah, true, let only me use it so. 👍

**Comment by lauthieb** [comment]
Thank you very much @BlackMix for these contributions anyway. Hope you enjoy code notes and feel free to ask if you have any question/suggestion.
