### ISSUE TITLE
Error on Travis CI

### ISSUE THREAD

**Issue by lauthieb** [lauthieb/code-notes#138]
**Describe the bug**
Error on Travis CI build : https://travis-ci.org/github/lauthieb/code-notes/jobs/691914972

@mszkb @kodaman2 do you have an idea to help me fix this issue? I've upgrade package-lock and clear the cache but I still have this error. :(

Thanks a lot.

**Comment by kodaman2** [comment]
Can you try this on travis.yml:

```
before_install: 
    - npm install -g node-gyp
```

**Comment by lauthieb** [comment]
Thanks @kodaman2, still an error: https://travis-ci.org/github/lauthieb/code-notes/builds/692065252

**Comment by mszkb** [comment]
Oh damn, it seems the upgrade to vue-cli 4 and electron 8 had some drawbacks.
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Browser_compatibility

Last row: Rest object (destructuring in objects) works only with node.js >= 8.3
If code-notes does not particular rely on an older node.js version, I would suggest upgrading to node.js 12 LTS.

**Comment by lauthieb** [comment]
I will try this, thanks @mszkb
