### ISSUE TITLE
add dart to language list

### ISSUE THREAD

**Issue by pahosler** [lauthieb/code-notes#139]
**Is your feature request related to a problem? Please describe.**
When creating a new note or displaying a gist dart formatting is not supported, and the code is labeled and displayed as plain text.

**Describe the solution you'd like**
add dart to language support

**Describe alternatives you've considered**
there are no available alternatives

**Comment by pahosler** [comment]
I would like to add a PR to the project.

I forked and added dart to the list of supported code formats.

I also fixed an error in types for `src/components/editor/Editor.vue` when being called from `NoteCard.vue`, where `NoteCard` height and width had string values and `Editor.vue` was expecting boolean values. I changed the type definitions in Editor to `String`

There are no breaking changes, code builds and runs after editing. If this minor change requires a  version change please let me know so I can update accordingly, if a PR is acceptable. I can add more of the available languages supported by brace if you like.

**Comment by mszkb** [comment]
PR active #141

**Comment by lauthieb** [comment]
Merged, thanks a lot guys.
