### ISSUE TITLE
Feature request: Link with Atom

### ISSUE THREAD

**Issue by Wikiki** [lauthieb/code-notes#14]
First of all: thanks for the job. It's a great tool :-D

Do you plan to integrate the tool with the Atom code editor ?

Regard

**Comment by lauthieb** [comment]
Hello @Wikiki 

Thanks for your issue :)
I don't plan to integrate code notes with Atom for the moment because there is a lot of IDEs and I don't have the time to integrate code notes on each IDEs... But if you want, you can do it, I will appreciate your PR :)
