### ISSUE TITLE
Unable to delete note

### ISSUE THREAD

**Issue by stolenusername** [lauthieb/code-notes#142]
**Describe the bug**
The delete button to delete a note doesn't appear to work.

**To Reproduce**
1. Create a new note.
2. Click on  the red trash can to delete the note.
3. Observe the note is note deleted.

**Expected behavior**
The note gets deleted or removed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Opens in an Electron window.
 - Version 1.2.4

**Comment by mszkb** [comment]
Thanks for the report. It is kinda strange that such functionality do not work after the migration. I will look into it :)
