### ISSUE TITLE
Application not working after update 1.2.4

### ISSUE THREAD

**Issue by m3l10da5** [lauthieb/code-notes#146]
**Describe the bug**
After update, Code-notes not working and display white screen (see attachment file)

**Desktop (please complete the following information):**
 - OS: Windows 10 (build 1903)

**Additional context**
![error](https://user-images.githubusercontent.com/65487640/85557562-2b529180-b628-11ea-8bcc-043a855294df.png)

**Comment by lauthieb** [comment]
Hi @m3l10da5 thanks for reporting this.

@mszkb @pahosler can you please try if you have this error on Windows?

**Comment by pahosler** [comment]
I have had this happen on occasion.
usually `ctrl + shift + F11` and then in the inspector `ctrl + r` will do a refresh and all is well. Another `ctrl + shift + F11` closes the inspector.

Ideally this shouldn't happen. 

Unfortunately I haven't had time to investigate to see what might cause this to happen or how to fix it.
Considering the underlying code is javascript, it could possibly be an async issue, that's where I'd start looking first.

**Comment by pahosler** [comment]
ok... update,

I haven't updated recently, and I haven't opened code-notes in a while, so this surprised me. It would not load any data. Even after `ctrl + r`, but I did get an error in the console about AppData/Roaming/code-notes/notes. I'm not sure what might have happened, after renaming code-notes to code-notes-old and restarting code-notes the app was back to normal but of course any local notes are gone.

I'll upgrade to the latest version this weekend, if I notice anything I'll post here. 
Anyone else, please also feel free to jump on this issue.

**Comment by sadikerd** [comment]
May I have the setup of the older version because of the this issue?

**Comment by sadikerd** [comment]
1.2.2 for example
