### ISSUE TITLE
Ability to sync gists with local notes, vice versa

### ISSUE THREAD

**Issue by flashadvocate** [lauthieb/code-notes#147]
Haven't investigated the feasibility of this yet, and would be happy to look at contributing to make this a thing, but in terms of safely storing a trove of notes, it would be utterly awesome to be able to sync notes between gists (pull all gists down into local, or conversely, push all local notes into gists). 

Might also make sense to incorporate a "secrets" tag that prevents automation from syncing a secret-tagged local note into gists.

**Comment by lauthieb** [comment]
Nice idea @flashadvocate thanks. I don't have time to make this true, unfortunately.
Feel free to help #121 made by @LucasVanHaaren. It converts local note to gist. All that remains is to do the opposite.

**Comment by flashadvocate** [comment]
Sure thing. I’ll check it out

**Comment by LucasVanHaaren** [comment]
Hi @flashadvocate, are you working on it ?
I can help you, or even start to develop this feature.

**Comment by flashadvocate** [comment]
> Hi @flashadvocate, are you working on it ?
> I can help you, or even start to develop this feature.

Sorry, I have been completely useless here because I've been swamped on other things
