### ISSUE TITLE
gripe - required fields

### ISSUE THREAD

**Issue by flashadvocate** [lauthieb/code-notes#148]
I am not a massively huge fan of the latest requirements placed on input. I should just need title and body. Having to add not only a file name but _also_ a description is a pretty big bump in workflow. Are either or both of these things actually needed?

**Comment by lauthieb** [comment]
Thanks @flashadvocate for this idea.

@stephengroat @mszkb @flashadvocate @bainternet @aspencer @slabruyere @pahosler @marvpaul @guastallaigor what's your point about this please?

For me, I don't think it's a problem if "description" and "filename" inputs would become not required.

**Comment by guastallaigor** [comment]
I agree, maybe change the order and put them  between Language and Content? :thinking:
