### ISSUE TITLE
Github Icon to "Show on Github" is broken

### ISSUE THREAD

**Issue by zacharyprice** [lauthieb/code-notes#165]
**Describe the bug**
Clicking on the GH icon for any Gist, whether secret or private, created recently or a while ago, doesn't open GH in the browser.

**To Reproduce**
1. Go to any gist in your app.
2. Click on the GH icon that states "Show on Github" onHover.
3. See error

**Expected behavior**
I would assume that clicking this icon would take me to its respective gist on Github.com.

**Screenshots**
<img width="997" alt="Screen Shot 2020-12-30 at 8 53 54 PM" src="https://user-images.githubusercontent.com/870971/103392019-82f31d80-4ae1-11eb-92d7-0c0c49461c9c.png">

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7

**Comment by lauthieb** [comment]
Thanks @zacharyprice for reporting this! Will investigate when I can 👌🏻

**Comment by zacharyprice** [comment]
You bet @lauthieb !

**Comment by zacharyprice** [comment]
:(
