### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by sadikerd** [lauthieb/code-notes#168]
**Not working on the windows 10**
There is only one white screen on the interface. All things disappear in 1 second.
I have tested the latest version. (Version 1.2.4)
I had the same issue on 1.2.3 as well.
But version 1.2.2 is working well on my system.

**Screenshots**
![image](https://user-images.githubusercontent.com/18291421/108226248-040f7e00-713d-11eb-82a7-11b358bdce95.png)

![2021-02-17_16-33-07](https://user-images.githubusercontent.com/18291421/108227199-f1497900-713d-11eb-8ce9-e6f51d33c3c2.gif)

**Desktop (please complete the following information):**
 - Windows 10 x64

**Comment by danielnovello** [comment]
I can second this

**Comment by lauthieb** [comment]
Thanks for reporting this!
Sorry I don't have a Windows computer to test easily...
I use Electron and thought that all works!
Is it possible to one of you to fix this issue?
Thanks a lot!
