### ISSUE TITLE
Note is not created if "." in the filename

### ISSUE THREAD

**Issue by shevabam** [lauthieb/code-notes#17]
### Current Behavior
In the window for creating a note, if I enter a filename with a ".", the note does not register.

### Steps to Reproduce (for bugs)
1. Create note
2. Fill "name" field
3. Fill "Filename" field with a "."
4. Click on "Create" button ; the note is not saved

### Your Environment
* Version used: v1.1.0
* Operating System and version: Windows 7 64 bits

**Comment by lauthieb** [comment]
Ok, thanks for the issue. I will fix it soon ;)

**Comment by sleeyax** [comment]
Is it just me, or is this still not fixed in v1.2.1?

**Comment by n-develop** [comment]
I just downloaded and installed v1.2.1 and it's not working yet.
In case it is important for reproduction: I use Windows 10 64 Bit

**Comment by acumulus8** [comment]
Getting the same issue with same version as  @n-develop

**Comment by lauthieb** [comment]
Hey @acumulus8, I will investigate if this happens always on v1.2.2

**Comment by bastienterrier** [comment]
Hello, I'm currently looking at your projet: great btw!
And I'm experiencing the same issue. After debugging the code and check on internet what's going wrong, I found this issue: https://github.com/louischatriot/nedb/issues/399
neDB does not support dot, neither MongoDB. (And they won't)

So, one possibility would be to encode the `.` to store the file in the DB during local file creation, and decode it during render :)
What do you think @lauthieb?

**Comment by lauthieb** [comment]
Thanks for the investigation @bastienterrier.
You’re right, sure that your solution could resolve this bug.

**Comment by wchen928** [comment]
Hi @lauthieb, I just downloaded the app this week and I'm still having the same issue. 

Is there anyone else working on this issue? May I help? Thank you for this project btw! It's great.

**Comment by lauthieb** [comment]
Not stale
