### ISSUE TITLE
sub category 

### ISSUE THREAD

**Issue by amirjani** [lauthieb/code-notes#20]
there are some language to save , but saved code has some sub categories too . 
for example for html and css 
language is HTML 
then there is no way to add HTML things like HTML related to button for example . 

### Expected Behavior
Can add sub category to each language

### Current Behavior
only language supported

**Comment by lauthieb** [comment]
Hello @amirjani, sorry I don't understand your request and your example. Can you please reformulate ?

**Comment by amirjani** [comment]
​thanks for your attention
​
each languages many component
for example
php has methods for storing data and it can be in so many different ways
but if we want add it only in description form we meet some problems
so we can have php language and component that user can add like storing
methods

thanks again

**Comment by lauthieb** [comment]
Oh okay, form example a tree like this :

|- JavaScript
|----- Async HTTP calls
|----- Array functions
|----- Cheat sheets
|- HTML
|---- Form
|---- Buttons
|---- Templates
|---- Starters

?

**Comment by amirjani** [comment]
​Is it possible now ? ​




<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>

**Comment by amirjani** [comment]
​yes , It's helpful for each programmer ​




<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>

**Comment by lauthieb** [comment]
Ok, I see, thanks it's a good idea. I develop code notes in my free time and I have a lot of work for the next version (v1.2.0). So I will bring that in the v1.3.0 ;)
Thanks.

**Comment by amirjani** [comment]
​thanks a lot
I'm learning electron
It's pleasure to help you

Any way wish you good luck ​




‌

**Comment by lauthieb** [comment]
Hello @amirjani, someone give me the idea to add some tags on a note. I think it's better than subdirectories. 
What do you think about this?
See #22

**Comment by amirjani** [comment]
I don't understand what the exact meaning of tag is here , 
I think they are same now 
It's better to have tag on each language and access them by its tags

**Comment by lauthieb** [comment]
tag are free words like hashtag, it does'nt refer to a specific language.
I want to keep Code Notes simple and subdirectories + tags will be difficult. I prefer the notion of tags but thanks for your idea !!

**Comment by amirjani** [comment]
I'm agree with you
good luck ​




<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>
