### ISSUE TITLE
[minor] portable version for linux

### ISSUE THREAD

**Issue by Kayoku** [lauthieb/code-notes#21]
Hi,

Create a portable version for Linux could allow user to use code-notes even in computer without root access. (For example, if you are student and you work at your university...)

This is a really minor issue.

Thanks!

**Comment by lauthieb** [comment]
Hello @Kayoku, thanks for your request. For the moment, I have a lot of features to develop and I'm not an Electron expert so I don't know how to resolve this. But, feel free to help me or I will do that one day :)
