### ISSUE TITLE
Feature - Tagging

### ISSUE THREAD

**Issue by david-mk** [lauthieb/code-notes#22]
Hello, thanks for making this awesome project!

I think a really helpful feature would to be able to tag code snippets. 

For example, if I have a bunch of react related snippets, it would be nice to be able to add and tag the snippets as "react" so they are easier to find later without being cluttered by the other snippets.

Let me know what you think.

**Comment by lauthieb** [comment]
Hello @david-mk, thanks for you request ;)

I have the same idea two weeks ago. But I saw that in Github gist, there's no tag so I've gave up but if you want this, I can do it in a new version. However, tags will only work in the local notes, not in gist ;)

**Comment by mdelantes** [comment]
Hello @lauthieb 

Thanks you for this project!

Tags will be a real improvement IMHO even if it works only with local notes.

**Comment by lauthieb** [comment]
thanks too @mdelantes, they will be present in the next version v1.2.0 ;)

**Comment by lauthieb** [comment]
@mdelantes @david-mk I prefer to add tag on a note instead tag on each file, are you agree ?

**Comment by mdelantes** [comment]
@lauthieb yes, sound great.

Will you plan to add filter by tags too 😇  ?

**Comment by lauthieb** [comment]
@mdelantes Yes, obviously :D
