### ISSUE TITLE
AppImage 1.2.4 not starting

### ISSUE THREAD

**Issue by Alegrowin** [lauthieb/code-notes#227]
$> ./code-notes-1.2.4-x86_64_aef5f804134fe8dd31e6cbba68fba92d.AppImage

Gtk-Message: 14:14:29.115: Failed to load module "appmenu-gtk-module"
Gtk-Message: 14:14:29.693: Failed to load module "appmenu-gtk-module"
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
(node:1462439) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:1462439) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
[1462439:0117/141431.232376:FATAL:gpu_data_manager_impl_private.cc(1034)] The display compositor is frequently crashing. Goodbye.

**Comment by Alegrowin** [comment]
Very nice project, good job btw. I am using 1.2.3 for now.

Let me know if you need more things for debugging purpose.

**Comment by lauthieb** [comment]
Hello @Alegrowin, thanks a lot for reporting this.
Unfortunately, I don't have time to maintain this, I hope someone in the community could help us 🙏
