### ISSUE TITLE
Support all brace mode

### ISSUE THREAD

**Issue by Alegrowin** [lauthieb/code-notes#228]
I wasn't able to find yaml in the list so I digged a little bit and noticed that brace 0.11.1 supports a lot of Language.

https://github.com/thlorenz/brace/tree/master/mode 

Any reason why there are missing mode in the implementation?

**Comment by lauthieb** [comment]
Hello @Alegrowin, thanks for your message.
No reason to answer your question, feel free to add them all in a PR :)
