### ISSUE TITLE
[Call for contribution] Is there someone with CSS/UX skills ?...

### ISSUE THREAD

**Issue by lauthieb** [lauthieb/code-notes#23]
Hello guys,

I write this issue because I found a bug in Code Notes and I'm calling you because I'm not really good in CSS...

### Expected Behavior
When I have a lot of languages, I can scroll to select the language I want

### Current Behavior

When there are a lot of languages and a small window height, we cannot see all languages

<img width="632" alt="capture d ecran 2018-02-08 a 09 59 33" src="https://user-images.githubusercontent.com/9600228/35964762-09b6db64-0cb9-11e8-920d-a78c6385207d.png">

### Possible Solution

Add a scrollbar in the left sidebar... Or if you have any idea ?

I hope I will find someone that could do this PR or give me some advice.

Thanks.

Laurent :)

**Comment by lauthieb** [comment]
@david-mk @kayoku @amirjani @gustavoFreireS @shevabam @Canyata @Julienh ?

**Comment by shevabam** [comment]
On the list <ul> in <aside>, try by putting in CSS `overflow: auto;`

Also, you must define a maximum height (max-height). You have to recover the height of the window.

![codenotes](https://user-images.githubusercontent.com/1798289/35966415-09aae822-0cbe-11e8-8344-c26aa8caeabd.png)

**Comment by lauthieb** [comment]
Thanks @shevabam !!!
I've just add this in the `<ul>` : 

```
overflow: auto;
max-height: 77vh;
```

**Comment by lauthieb** [comment]
FYI : I made a donate part in the [website](https://lauthieb.github.io/code-notes#download) if you want to thank and motivate me... :)
