### ISSUE TITLE
32-bit Windows compatibility

### ISSUE THREAD

**Issue by SolidSnakeFox** [lauthieb/code-notes#27]
Hi,

My question is simple :
Is it possible to have a compatible version on a 32-bit Windows?

### My Environment
* OS: Windows 7 Pro 32-bit

**Comment by lauthieb** [comment]
Hello @SolidSnakeFox, I don't know, I've just used the electron-builder in windows mode.
Feel free to contribute if you know how to generate an executable of Code Notes in win 32-bit.
