### ISSUE TITLE
Convert a local snippet to gist

### ISSUE THREAD

**Issue by shevabam** [lauthieb/code-notes#33]
Hi,

Have the possibility to convert a local code to gist.

**Comment by lauthieb** [comment]
Hello @shevabam, oh I like your idea, thanks ;)

**Comment by didlawowo** [comment]
any new about this issue ? should be usefull to save local in cloud or in github.

**Comment by lauthieb** [comment]
hello @didlawowo, i plan to develop this in the next minor version. I work on my free time, so sorry for the delay :)

**Comment by LucasVanHaaren** [comment]
Hello, I'm interested in this feature.
Can I try to contribute to its development?

**Comment by lauthieb** [comment]
Hello @LucasVanHaaren, yes feel free! :) Thanks!!!

**Comment by LucasVanHaaren** [comment]
Great ! I just have a quick question about the implementation.
Once the local note is exported to gist, must the local note be deleted ?
If yes, should we have to ask for confirmation (e.g. via a modal window) ?

**Comment by lauthieb** [comment]
Yes good idea. For me, once a local note is transfered to gist, we should ask for confirmation and redirect to gists tab. What do you think about this @shevabam ?
