### ISSUE TITLE
Gists sometimes takes a lot of time

### ISSUE THREAD

**Issue by matlink** [lauthieb/code-notes#35]
When using gists, sometimes it is loading forever with the blue circle turning around.
To resolve, I need to spam 'local' and 'gists' again until I get my gists.
* Version used: 1.2.0
* Operating System and version: ubuntu 16.04

**Comment by lauthieb** [comment]
Hello @matlink, thanks... But it's weird because when you click on Gists, it's just an async call to Github API, so I don't know why you have to spam "local" to see it works on gists...

**Comment by matlink** [comment]
It might be due to the connexion ...

**Comment by lauthieb** [comment]
There's a new release including this subject 🎉
https://github.com/lauthieb/code-notes/releases/tag/1.2.1
