### ISSUE TITLE
Please gitlab snippets support...

### ISSUE THREAD

**Issue by roboto-cloud** [lauthieb/code-notes#36]
**Awesome project!!!**

_here an early adopter asking for gitlab snippets support, it is on the Road map?_

Congratulations!

**Comment by lauthieb** [comment]
Hello @roboto-cloud, thanks for your proposition. I can plan this if you want, I have a lot of work and I code on Code Notes on my free time so I think I can do this in v1.4... :)

**Comment by roboto-cloud** [comment]
hi @lauthieb thanks for plan it :grinning:

**Comment by mlanner** [comment]
+1

**Comment by vosamoilenko** [comment]
+1

**Comment by bastienterrier** [comment]
I could try to add the Snippets support with the https://github.com/node-gitlab/node-gitlab library, @lauthieb what do you think?

**Comment by lauthieb** [comment]
Nice, give it a try if you want! Thank you very much @bastienterrier
