### ISSUE TITLE
Feature request Export/Import Local snippet

### ISSUE THREAD

**Issue by Erreur32** [lauthieb/code-notes#40]
It would be nice if we can import or export somes snippets locally.  Via file text or other ?

_Where is store the local snippet ?_

I love this tool :)

**Comment by liamdigitalstorm** [comment]
Yes, this needs to be a feature!! Looked through the actual app files and does not seem to be a basic way of storing the files you make. Please!!

**Comment by lauthieb** [comment]
Hello @Erreur32 and @liamdigitalstorm, I plan to do this in the next minor version.
Sorry for the delay, I develop code notes on my free time.
Would any of you wish to contribute ?
Thanks for you reports :)

**Comment by eriveraa** [comment]
Hi, i want to backup my code snippets, what files should i save or rescue before format my machine? is there a folder or database to save?. Please your help.

**Comment by lauthieb** [comment]
Hi @eriveraa. As you can see in the code, the notes and settings are in the "userData" directory of this application:
* Windows 7, 8.1, and 10: C:\Users\<username>\AppData\Local\code-notes
* Mac OS X El Capitan: Users/<username>/Library/Application Support/code-notes
* Linux: /home/<username>/.config/code-notes

Inside this folder, you will have "notes.db" and "settings.db". You will be able to backup easily 😎 

Btw, I will try to develop this feature.

**Comment by sadikerd** [comment]
It doesn't work for me!!! i saved all snippets ( i passed 1 hour) then totally white screen. And the repository is not like mentioned earlier
It is like this;
Windows 7, 8.1, and 10: C:\Users[username]\AppData\Local\Programs\code-notes

**Comment by lauthieb** [comment]
Thanks for reporting @sadikerd, sorry again. Check my comment https://github.com/lauthieb/code-notes/issues/119#issuecomment-563228788 if you want to retrieve your notes and rollback to 1.2.2 version of Code Notes.
We are a free & open source project. Today, I don't have a lot of time to maintain it. We will try to fix it when we will find someone ready to test it in development and see the console errors for example.
