### ISSUE TITLE
Syntax highlight additions

### ISSUE THREAD

**Issue by Taz8du29** [lauthieb/code-notes#41]
Hello !

It'd be nice if you added C, C++ (maybe x86_64 asm too ?) and some more languages to syntax highlighting.

Thanks you !

**Comment by sdhutchins** [comment]
Just to add....`R` is one of the most popular languages. Should probably be included.

**Comment by sdhutchins** [comment]
I'd be happy to add R if you could show me where that code is being processed in the source code. @lauthieb

**Comment by lauthieb** [comment]
There's a new release including this subject 🎉
https://github.com/lauthieb/code-notes/releases/tag/1.2.1

**Comment by sdhutchins** [comment]
Awesome!

**Comment by lauthieb** [comment]
Sorry @sdhutchins, I've forgotten R lang, I will republish it in few minutes 😃

**Comment by sdhutchins** [comment]
lol @lauthieb no problem! I can wait.

**Comment by lauthieb** [comment]
@sdhutchins it's okay :)
