### ISSUE TITLE
Manage Languages

### ISSUE THREAD

**Issue by paulushcgcj** [lauthieb/code-notes#44]
It would be awesome if it supports managing languages manually, like if you can`t find a language in dropdown menu, you can simply add it.

This way the number of issues based on language will be reduced.

I know that some of the "Custom Language" will not have some code coloring, but this will help us separate our snippets.

### Expected Behavior

On dropdown, you should select your language, or in case it doesn't, simply type it, and it will be added to your snippet dropdown.

You can limit it to local snippets only, if this would cause some issue on github gists.

### Current Behavior

Right now, the app only support fixed languages.

### Possible Solution

Let the dropdown accept text like a filter, but in case you didn't find the language, add it.

**Comment by lauthieb** [comment]
Hi @paulushcgcj , thanks a lot for your feature request !
I would appreciate to make this but I don't have any time now... 😟
Feel free if you want to help me.
