### ISSUE TITLE
Add Liquid Programming Lang.

### ISSUE THREAD

**Issue by Benwebdev** [lauthieb/code-notes#45]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Add the programming language Liquid. 

**Describe alternatives you've considered**

Add the programming language Liquid. 

**Additional context**
N/A

**Comment by lauthieb** [comment]
There's a new release including this subject 🎉
https://github.com/lauthieb/code-notes/releases/tag/1.2.1

**Comment by Benwebdev** [comment]
Woop! Thank you @lauthieb
