### ISSUE TITLE
Don't ask for a file name, just generate one

### ISSUE THREAD

**Issue by krainboltgreene** [lauthieb/code-notes#48]
I want to offload notes quickly. Forcing me to figure out a file name slows me down. See: Github Gists.

**Comment by lauthieb** [comment]
Closed by @slabruyere on #51 
Thanks!!!

**Comment by lauthieb** [comment]
There's a new release including this subject 🎉
https://github.com/lauthieb/code-notes/releases/tag/1.2.1
