### ISSUE TITLE
Notes require "valid" file names, but don't tell you that and also don't tell you what valid means

### ISSUE THREAD

**Issue by krainboltgreene** [lauthieb/code-notes#49]
Latest version doesn't let you create a note if the file name is "bad" but never tells you it's bad or what's wrong with it.

**Comment by lauthieb** [comment]
Thanks for your report @krainboltgreene, this issue was closed in #51

**Comment by lauthieb** [comment]
There's a new release including this subject 🎉
 https://github.com/lauthieb/code-notes/releases/tag/1.2.1
