### ISSUE TITLE
Theme/Colour Options

### ISSUE THREAD

**Issue by jordanjoecooper** [lauthieb/code-notes#54]
As it stands there are no theme options outside of the default.

**Describe the solution you'd like**
Multiple theme options preferably 'Dark' & 'Light' options for an existing example of what this could look like take a look at https://joplin.cozic.net/ 

**Describe alternatives you've considered**
As a longer term alternative there could be an options menu with a styling based option, if SCSS was used and vars set for the background / font colours the styling menu could allow a user to change those vars and the colours of each different area of the app.

**Comment by lauthieb** [comment]
Nice, thanks for your request @T4JC.
Feel free if you want to implement this in the next version.
I can answer your questions about the code.

**Comment by sleeyax** [comment]
I'd like to see this feature in feature releases as well, is anyone actively working on this?
