### ISSUE TITLE
Issue creating a note with multiple files

### ISSUE THREAD

**Issue by ztcdeveloper** [lauthieb/code-notes#55]
**Describe the bug**
You can't manage multiple files when creating a note. Deleting a note causes the "Create note" modal to close.

**To Reproduce**
1. Open the add note modal
2. Fill it out, but don't save
3. Add a file and then delete that file
4. Modal closes without saving and all work is lost

**Expected behavior**
I expected the modal to remain open so I could save my note.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by lauthieb** [comment]
Thanks @ztcdeveloper for reporting this bug. I will fix it asap 👍

**Comment by lauthieb** [comment]
@ztcdeveloper but I can't reproduce 😞 
![feb-15-2019 09-31-37](https://user-images.githubusercontent.com/9600228/52844282-85724700-3104-11e9-9358-ce5b51419980.gif)

**Comment by sleeyax** [comment]
I have the same operating sytem and I'm able to reproduce this error. @lauthieb, make sure to click the red delete button after adding an additional file. 
![image](https://user-images.githubusercontent.com/30344294/52860960-43132f00-3131-11e9-940f-50f55a207eca.png)

When I tried this, the modal closes and electron reloads itself. Oddly enough, the 'Add a file' feature works fine after that.

**Comment by lauthieb** [comment]
Okay thanks @sleeyax :)
I reproduce when I type nothing in the other file. Thanks! I will investigate.

**Comment by ztcdeveloper** [comment]
Thanks for looking into this @lauthieb! Below shows the process of reproducing. As @sleeyax mentioned, it seems to behave normally after the first time it fails and doesn't have any more problems until closing the application and then re-opening. The white flash seen in the capture occurs when clicking the delete button.

![bug_capture](https://user-images.githubusercontent.com/43078354/52892666-6d70e680-3149-11e9-9869-9826dc57cf5c.gif)

**Comment by Shhzdmrz** [comment]
Want to work on it but for me this issue is not appearing in Windows 10. Would be better if we have more information to reproduce it.
