### ISSUE TITLE
Create a VS Code plugin

### ISSUE THREAD

**Issue by lauthieb** [lauthieb/code-notes#56]
**Is your feature request related to a problem? Please describe.**
It will be great to have a VS Code plugin linked to Code Notes. No, it's not related to a problem but we would be even more productive if our notes were in our code editor.

**Describe the solution you'd like**
With this plugin, we would be able to:

- retrieve our code notes
- create a new one like in the app or from a file
- read (copy to clipboard) update/delete our existing notes
- Sync with our Github Gists

Feel free to complete this feature request 😃 

Thanks @EmmanuelDemey & [Luis Pexoto](https://twitter.com/LuisFP1986) for this **great** idea!

**Comment by LebCit** [comment]
Bonjour @lauthieb 
Je saisis l'occasion pour écrire en français dans le monde du code (rarissime) 🤣 
Tout d'abord pour vous félicitez de cet outil simple, intuitif, fiable, rapide d'exécution et indispensable pour garder des notes ou blocs de codes synchronisées avec gist.
Je cherchais un outil à cet effet et j'ai opté de tester le vôtre, en premier, parmi quatre autres "candidats", et je suis ravi ! Même plus besoin de tester les autres 😃 
Un plugin pour VS Code serait un atout majeur pour faire connaître code-notes à plus de développeurs.
Donc, **+1 for  Create a VS Code plugin**
Bien à vous, et merci pour votre temps et tous vos efforts !

**Comment by matfire** [comment]
I could try and do this; I've been thinking of learning how to create vs code extensions
