### ISSUE TITLE
Filename cannot contain "."

### ISSUE THREAD

**Issue by n-develop** [lauthieb/code-notes#59]
**Describe the bug**
When the filename contains a dot ( . ), the note is not created.
This bug was already reported in #17. But as this is already closed, I created this isuses.

**To Reproduce**
1. Click on 'Create note'
2. Fill all necessary fields
3. In the Filename field, use a value that contains a dot like 'Test.cs'
4. Click on 'Create'

**Expected behavior**
The note should be created and shown

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.2.1

**Comment by lauthieb** [comment]
Thanks for reporting 👍

**Comment by lauthieb** [comment]
I will fix it asap
