### ISSUE TITLE
Slack channel

### ISSUE THREAD

**Issue by igneel64** [lauthieb/code-notes#63]
Hey, how about adding a slack channel for this project. This way we can manage questions/requests better and build more responsiveness for those that want to contribute :)

**Comment by lauthieb** [comment]
Great idea! I will create this slack pretty soon :)
Thanks @igneel64

**Comment by lauthieb** [comment]
Here it is 🎉 
I prefer Gitter for this type of chat room : https://gitter.im/code-notes/community
The goal will be to be more responsive about ideas of evolution and bug fixes. So, Code Notes would become a living product more powerful!
Many thanks for your idea @igneel64 ❤️
