### ISSUE TITLE
Share Notes

### ISSUE THREAD

**Issue by herrozerro** [lauthieb/code-notes#65]
**Is your feature request related to a problem? Please describe.**
I am looking for a solution to share notes with my team, we even have started thinking about a common github account and sharing it to get common gists.  

It would be great to change or add another local location, for example a network share that multiple users could access.  Or putting a folder into google drive.

**Describe the solution you'd like**
An option to add another local location.  Click a dialog and navigate to a folder and then it would be available for under the notes section.

**Describe alternatives you've considered**
Sharing a common github account, but that opens up issues with sharing accounts.

**Additional context**
I think this app is great!  But it just needs a few features to make it more team friendly.

**Comment by lauthieb** [comment]
Thanks a lot for this big idea and feature request @herrozerro.
Unfortunately, I think it will be pretty difficult to add this now.
I code on my free time and it's a big task :(
Feel free if you want to help me and we will plan this feature request.

**Comment by herrozerro** [comment]
@lauthieb I am not an electron developer, but I can try.  I don't know the limitations of electron , but ff something like that is possible I could try to contribute.
