### ISSUE TITLE
Infinite loop on loading when create file (local mode)

### ISSUE THREAD

**Issue by Arkedrille** [lauthieb/code-notes#66]
I can't create note : when I create one, I stay on "loading" for an infinite amount of time.
I use Fedora 29 and the appimage. Everything works, my others appimage still functioning.
See pictures for more information.

When I create on "create" the infinite loop begin.
If I click on "Add a file" then on the trash icon and click on "create", the file is created.

![codenotesbugcreate](https://user-images.githubusercontent.com/44497977/54015898-7a4d8c80-4181-11e9-9d80-2a2c2e60e8b4.png)
![fedoraneofetch08-03-2019](https://user-images.githubusercontent.com/44497977/54015899-7a4d8c80-4181-11e9-971e-aee4b2f2e2a9.png)
![codenotesbugcreate](https://user-images.githubusercontent.com/44497977/54015906-82a5c780-4181-11e9-9a89-c82e31692b93.png)
![fedoraneofetch08-03-2019](https://user-images.githubusercontent.com/44497977/54015907-82a5c780-4181-11e9-9575-f82b286b43ec.png)

**Comment by Arkedrille** [comment]
trash the .appimage and try with another : same.

**Comment by probil** [comment]
Hi @Arkedrille 
I'm unable to reproduce it on my machine: Archlinux with Cinnamon
Which versions are you using?
