### ISSUE TITLE
Very small edit window for text

### ISSUE THREAD

**Issue by Kondzolko** [lauthieb/code-notes#69]
Hello everyone looks like the very cool program but only one features what I think it necessary provide, it needs to make a window where you create a note bigger, for me, it very hard writes some information it in this so small window, if you can make this window bigger it will a greate!

Best regards,
Andrew

**Comment by probil** [comment]
Font size is also quite small for retina display

**Comment by probil** [comment]
Don't you mind if I take it?
I've already solved an issue with font size and I think I can implement fullscreen mode

**Comment by probil** [comment]
Here is a PR #103. Review please
