### ISSUE TITLE
Change internal data structure to save one created code snipped in one file

### ISSUE THREAD

**Issue by marvpaul** [lauthieb/code-notes#71]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I wan't to export my code notes or accessing them e.g. from terminal. 

**Describe the solution you'd like**
It would be very helpful if the app internally stores one code note per file, using the filename which is provided by the user, so you can access it from outside the app.
E.g. in case I'll create a code note with filename sample.sh, a file named sample.sh could be created in the app / program folder.

**Comment by lauthieb** [comment]
Hello @marvpaul!
Thanks a lot for this great idea of improvement.
I don't have time nowadays to maintain Code Notes but I would love to help you if you want to make a Pull Request resolving your issue.
Regards :)

**Comment by lauthieb** [comment]
Closed with #74 :tada: 
Thanks @marvpaul ❤️
