### ISSUE TITLE
Plans to support github enterprise for Gists?

### ISSUE THREAD

**Issue by flashadvocate** [lauthieb/code-notes#75]
Just curious if there are plans to support Github Enterprise?

**Comment by lauthieb** [comment]
I @flashadvocate, sorry but there's no plan to support Github Enterprise for the moment.
Do you know if this could be simple to integrate?

**Comment by kodaman2** [comment]
@flashadvocate out of curiosity what error are you getting? looks like enterprise uses the same api. Did your token not work?

**Comment by kodaman2** [comment]
Nevermind, looked at the code and this repo is using octokit for authentication, it should still be a relatively easy change just need to give the custom enterprise url to the octokit constructor. I might be able to submit a PR.

**Comment by kodaman2** [comment]
Anyone working on this already?

**Comment by lauthieb** [comment]
Let's go @kodaman2 if you want 😃 
Thanks a lot!

**Comment by kodaman2** [comment]
@lauthieb cool, I'll submit a wip PR so people know is in progress. 

@flashadvocate 

- Would you be able to test by building the project locally? 
- What is your company GHE url?

I'm going to hardcode the url the octokit constructor to make sure it works as a start, but I don't have access to an enterprise account, I suppose you can't create a dummy account for us to test it would make this a lot quicker.

**Comment by flashadvocate** [comment]
@kodaman2 yes I'd be willing to help.

Company GHE is github.ncsu.edu

**Comment by kodaman2** [comment]
@flashadvocate whenever you get a chance this week please test PR #95 .

**Comment by flashadvocate** [comment]
Just wanted to say thanks to @kodaman2 for his work on this. Looking forward to taking advantage of gists on enterprise github!  🎉 🍻

**Comment by kodaman2** [comment]
You're welcome, glad to bring in ghe auth to code-notes.
