### ISSUE TITLE
Searchbar is case sensitive

### ISSUE THREAD

**Issue by KeziahMoselle** [lauthieb/code-notes#8]
# Case sensitive

### Expected Behavior
If we write "sum" we are supposed to see the result corresponding to "Sum"

### Current Behavior
![Search for sum](https://puu.sh/zf9HH/661ef6b7c0.png "Search for sum")
![Search for Sum](https://puu.sh/zf9Ii/2016ef032b.png "Search for Sum")

### Your Environment
* Version used: v1.0.0
* Operating System: Windows 10

**Comment by lauthieb** [comment]
Oh thanks, I will fix that ;)
