### ISSUE TITLE
Feature Request - extra fields

### ISSUE THREAD

**Issue by GAZelenka** [lauthieb/code-notes#80]
Hi Laurent, I'm not a programer (I use code I find on the web to create my PowerShell and Javascript queries!) I'd find it really useful to have a field for:
- Source - so I can find the original code web site
- Works (Yes/No) I've tried a large amount of code snippets that don't work in my environment - it would be  nice to be able to save an tag these, so I don't keep re-trying something that doesn't work.
This information could be saved as a comment in the snippet, but it would be nice to be able to filter and search on these criteria as well.
Thanks very much for your help.
Kind regards
Gerhard

**Comment by jack-chapman** [comment]
I feel like a generic 'notes' section for each snippet (or file) could be very useful.
I like the idea of being able to link your snippet up to a source on the web, so adding clickable links to a 'notes' section could be really valuable.

For the 'works' yes/no idea, you could probably use the tags feature. It's not very clear, but you can use the search bar to filter the snippets by tag.

**Comment by kartik-budhiraja** [comment]
@lauthieb can I look into this issue if it's available?

**Comment by lauthieb** [comment]
@kartik-budhiraja yes for sure!
How do you plan to implement this "meta" part?

**Comment by kartik-budhiraja** [comment]
@lauthieb  Sorry I was a bit occupied, I am going to look into it this week, will ping you here with details about how I envision to the solution to be!

**Comment by kartik-budhiraja** [comment]
@lauthieb apologies for the delay.

So I think we can add an input for the source information about the code snippet, which could be displayed as `b-link`.
Regarding the notes section, isn't description input supposed to be for this purpose only?
