### ISSUE TITLE
Feature request: "Frequently used file types"

### ISSUE THREAD

**Issue by benhalpern** [lauthieb/code-notes#91]
**Is your feature request related to a problem? Please describe.**
I can tell I'm going to want to use the same programming languages pretty consistently. It would be nice if I were presented with frequently/recently used ones.

**Describe the solution you'd like**
Next to the dropdown, there could be a couple clickable options.

**Describe alternatives you've considered**
Alternatively, having a typeahead instead of a dropdown could make this less necessary (though still might be useseful)

**Additional context**

![Screen Shot 2019-10-01 at 4 48 27 PM](https://user-images.githubusercontent.com/3102842/65999626-c8064b00-e46b-11e9-977a-97692c13ac12.png)

**Comment by lauthieb** [comment]
Hi Ben!

What an honor to receive a feature request from you. 
Thanks a lot for the visibility that my DEV.to articles brings to Code Notes project.

It's a pretty good idea. I label it now for Hacktoberfest! Hoping someone could help me make this available! 💡

**Comment by sahilsharma011** [comment]
I'm interested in working in this. What I was thinking that maybe we could sort programming languages by their frequency of usage in descending order. And also implement a searchable dropdown.

**Comment by kartik-budhiraja** [comment]
@sahilsharma011 Are you still working on this issue if not, I would love to take it over. :)

**Comment by lauthieb** [comment]
Hi @kartik-budhiraja, I don't know but feel free to ask @sahilsharma011 :D 
Thanks a lot!!

**Comment by sahilsharma011** [comment]
@kartik-budhiraja no I'm not working on this. Feel free to work on this.
