### ISSUE TITLE
Upgrade from Vue CLI 2 to Vue CLI 4

### ISSUE THREAD

**Issue by lauthieb** [lauthieb/code-notes#94]
Hi everyone!

I need help to migrate and refactor the codebase from Vue CLI 2 to Vue CLI 4.

Thanks a lot in advance for your help ❤️

**Comment by thauska** [comment]
I can do this

**Comment by lauthieb** [comment]
@thauska feel free!
Thanks a lot in advance! 😃💯

**Comment by Seanmclem** [comment]
Vue 3 is not released?

**Comment by thauska** [comment]
I think he means upgrade for Vue CLI 3

**Comment by lauthieb** [comment]
Yes sorry :)

**Comment by probil** [comment]
Consider upgrading to Vue CLI 4 (since released recently)

**Comment by nkondra** [comment]
Is this still in progress? I would be happy to give this one a go.

**Comment by lauthieb** [comment]
Thanks a lot @nkondra !!
Maybe you can check this with @thauska!

**Comment by algobot76** [comment]
Any progress on this issue? I may take a look and see if I could do the upgrade over the weekend.

**Comment by mszkb** [comment]
I assume nobody is working right now on this issue.

I am currently working on a solution to do the migration from vue-cli 2 to vue-cli 3. I probably need a couple days. There would be some breaking changes. I'll drop a message if some obstacles occur.

**Comment by mszkb** [comment]
I see there is one big problem with the updated vue-cli 4 and vue tooling in general.
https://vuejs.org/v2/guide/single-file-components.html#What-About-Separation-of-Concerns

The component files are seperated into html, scss and the vue file. According to the documentation and my current progress, I probably have to move all html file contents inside the vue files.
Problem right now: Outsorucing the html \<template src="..."\>\</template\> might not work anymore (I am not 100% sure). The documentation only have the **src** at the script and style tag but at the template.

@lauthieb What do you think? Are you okay to put all html contents into the vue files?

**Comment by lauthieb** [comment]
Hi @mszkb, thanks a lot for investigating this issue!

To answer your question, I think the vue files will be very big if we put html contents into them... There's no solution to keep `<template src="...">` inside those .vue files?

**Comment by probil** [comment]
I would suggest moving templates into vue files.
It would make files bigger for sure but it also help to spot huge component which need separation. Moreover, placing templates into vue files is kind of a standard nowadays and having that would improve maintainability as more people are familiar with it

**Comment by mszkb** [comment]
I will investigate a little bit, but as @probil said, nowadays you put everything into the vue files (even css). If your vue files are getting too big then the best idea is to create a new component.

**Comment by lauthieb** [comment]
Okay, thanks guys! 2 years I've switched to React so I trust you for current best practices. 
So you can do this like this @mszkb :-)
Thanks a lot for your help improving Code Notes.

**Comment by mszkb** [comment]
@lauthieb I am pleased to help.

Right now I am stuck at the unit and e2e tests. There are no meaningful unit tests and the karma config is not compatible with vue-cli 4. Therefore I'd like to use Jest because vue-cli provides nice support. I try to replicate the e2e tests with jest aswell. Is that okay?

**Comment by lauthieb** [comment]
Yes feel free for this @mszkb

**Comment by lauthieb** [comment]
We can now close this issue thanks to @mszkb!

**Comment by lauthieb** [comment]
@mszkb 
As I mentioned in #135, there's a problem...
When I did npm run build:mac and installed with the new 1.2.4 dmg file, I've lost all my notes. Fortunately, when I reinstall the 1.2.3 version my notes come back.
Can you please check this problem?
I will let your commit on master but don't make a release until this work again.
Thanks!

**Comment by mszkb** [comment]
Additional config was needed: https://github.com/lauthieb/code-notes/issues/94#issuecomment-631147962
